### ISSUE TITLE
Make repo public - Once rename has been completed

### ISSUE THREAD

**Issue by helendduncan** [alan-turing-institute/eider#81]
Find optimal time to make Repo public - do we want to give the caveat that it is a WIP.
Do we want to wait until just prior to paper publication

Will opening earlier allow us to be less "precious" about things. Will also allow testing.

@simonrnss @louisaslett Please do say if you have objections to this repo becoming public in the next couple of weeks - (once it is renamed to "EIDER" everywhere it needs to be)

@catavallejos is happy for this to happen as long as it is open before a paper submission!

**Comment by yongrenjie** [comment]
Done
