### ISSUE TITLE
Add this set of 'real-life' example to the docs

### ISSUE THREAD

**Issue by yongrenjie** [alan-turing-institute/eider#90]
1. On the R command line, run
    ```R
    install.packages('devtools')
    devtools::install_github('alan-turing-institute/eider')
    ```

   Note that the transitive dependencies take a very long time to install if you are starting from a fresh R installation.

2. Download this zip file: [eider_test.zip](https://github.com/alan-turing-institute/eider/files/14751019/eider_test.zip) (I don't want to commit it to the repo without a good reason)

3. Unzip, `cd` inside the `eider_test` directory and run (from the shell)
    ```bash
    Rscript eider_test.R
    ```

    or equivalently, from the R console, run

    ```R
    source('eider_test.R')
    ```

    _(Note: it is not mandatory to run from the `eider_test` directory, but if you use a different working directory, the relative paths to the JSON files in the script must also be changed accordingly.)_

    As of the time of writing this issue, the expected output is as follows:

    ```R
    Rows: 9
    Columns: 13
    $ id                             <dbl> 0, 1, 2, 3, 4, 5, 6, 7, 21
    $ total_ae_attendances           <int> 9, 3, 3, 4, 2, 5, 6, 8, 0
    $ total_neurology_ae_attendances <int> 2, 0, 1, 0, 1, 0, 0, 0, 0
    $ days_since_last_ae_visit       <dbl> 1189, 1189, 1221, 1231, 1407, 1422, 126…
    $ has_visited_ae                 <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 0
    $ num_prescriptions_since_2016   <int> 10, 7, 14, 21, 5, 8, 8, 10, 0
    $ unique_bnf_sections            <int> 4, 3, 4, 6, 3, 5, 3, 3, 0
    $ num_psychotherapy_stays        <int> 0, 2, 3, 1, 1, 5, 5, 3, 0
    $ num_psychotherapy_episodes     <int> 0, 3, 4, 1, 2, 6, 6, 4, 0
    $ total_days_in_hospital         <dbl> 2, 9, 15, 7, 8, 19, 14, 3, 0
    $ years_with_asthma              <dbl> 3, 4, 40, 40, 40, 40, 40, 40, 40
    $ parkinsons_and_bnf0114         <dbl> 2, 1, 0, 2, 1, 1, 0, 0, 0
    $ parkinsons_and_bnf0114_2       <dbl> 7, 4, 0, 7, 4, 4, 0, 0, NA
    ```

    Any warning or error should be considered a bug.

**Comment by yongrenjie** [comment]
[eider_test.zip](https://github.com/alan-turing-institute/eider/files/14751017/eider_test.zip)

**Comment by yongrenjie** [comment]
tested on personal laptop and seems good

**Comment by crangelsmith** [comment]
Works well for me!

**Comment by yongrenjie** [comment]
Closing as duplicate as this has been lumped into #85
