### ISSUE TITLE
Black text/blue background

### ISSUE THREAD

**Issue by louisaslett** [alan-turing-institute/eider#96]
I've done most of the final check tweaks I spotted myself in a pull request which I'm putting in now.  However, I thought I better create an issue on this one as it is more subjective (and I'm also not sure what pipeline you've setup for `pkgdown`) ...

It might be my aging eyes, but I think the black text on the blue header is really hard to read on the [package website](https://alan-turing-institute.github.io/eider/).  Should we change the non-hover text colour to white perhaps?  Or change the blue background?  I don't mind what the change is really once it is a bit better contrast.

**Comment by yongrenjie** [comment]
That's so odd, I don't know why the text comes up as black — the theme shows that it's supposed to be white: https://bootswatch.com/zephyr/

It is a problem though, it's very poor contrast! I've changed the theme now so should be better.
